language: node_js
node_js: node
sudo: false

cache:
  directories:
    node_modules

before_script:
  - npm install -g greenkeeper-lockfile@1
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm i -g codecov
  - codecov
